In [9]:
import numpy as np

In [38]:
a = np.array([1,2,3], dtype='int32') #we can jus specify the size if we want to save memory
print(a)

[1 2 3]


In [43]:
b = np.array([[1,2,3],[2,3,4],[5,6,7]])
print(b)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [44]:
#to get dimension

b.ndim

2

In [45]:
#get shape
b.shape

(3, 3)

In [46]:
#get type
a.dtype

dtype('int32')

In [47]:
#get size(size in bytes)
b.itemsize

4

In [50]:
#get total size
a.size * a.itemsize #=a.nbytes

12