In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])
print(a)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [3]:
#to get specific element
a[1,4]

8

In [4]:
#to get specific row
a[1, :]

array([4, 5, 6, 7, 8, 9])

In [5]:
#to get specific column
a[:, 3]

array([4, 7])

In [6]:
#[array index ,first index : end index : step size]
a[1 , 2:5:2]

array([6, 8])

In [7]:
#updating
a[1,5] = 10
print(a)


[[ 1  2  3  4  5  6]
 [ 4  5  6  7  8 10]]


In [8]:
a[:, 4] = [3,4]
print(a)

[[ 1  2  3  4  3  6]
 [ 4  5  6  7  4 10]]


In [9]:
#all 0s matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#all 1s matris
np.ones((2,1,2,1))

array([[[[1.],
         [1.]]],


       [[[1.],
         [1.]]]])

In [11]:
#any other number matirx
np.full((2,3), (88))

array([[88, 88, 88],
       [88, 88, 88]])

In [12]:
#if ypu wanna copy shape of another array
np.full_like(a, 4)
#another way
np.full(a.shape, 5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [13]:
np.random.rand(2,7)

array([[0.24626437, 0.7970597 , 0.28623944, 0.53050339, 0.54102008,
        0.23612921, 0.59592204],
       [0.95846833, 0.23811513, 0.88121317, 0.070167  , 0.85450323,
        0.58152475, 0.07574876]])

In [14]:
np.random.randint(1,88, size=(3,3))

array([[ 7, 69,  7],
       [82, 11, 23],
       [23, 27, 86]])

In [15]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
#repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [17]:
arr = np.array([[[1,2,3], [4,5,6]]])
r1 = np.repeat(arr, 5, axis=0)
print(r1)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1]= 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
#copying contents wihtout distorting the original one

a= np.array([1,2,3])
b=a.copy()
b[0]=100

print(b)

[100   2   3]


In [20]:
a=np.array([4,8,16])


In [21]:
a/2

array([2., 4., 8.])

In [22]:
a*2

array([ 8, 16, 32])

In [23]:
b= np.array([1,2,3])
a+b

array([ 5, 10, 19])

np.sin(b)

In [24]:
a = np.ones((3,3))
print(a)
b = np.full((3,), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[2 2 2]


array([6., 6., 6.])

In [25]:
c = np.array([[1,1,3],[2,0,4],[3,0,5]])
np.linalg.det(c)

2.0000000000000004

Statistics

In [26]:
a = np.array([[1,2,3],[4,5,6]])

np.max(a, axis = 0)

array([4, 5, 6])

In [27]:
np.min(a, axis=1)

array([1, 4])

In [29]:
before = np.array([[2,4,5],[7,8,9]])
print(before)

after = before.reshape(3,2)
print(after)

[[2 4 5]
 [7 8 9]]
[[2 4]
 [5 7]
 [8 9]]


In [30]:
after.shape

(3, 2)

In [31]:
#vertical stack
v1 = np.array([[4,5,6],[1,2,3]])
v2 = np.array([7,8,9])

np.vstack([v1,v2,v2])

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9],
       [7, 8, 9]])

In [32]:
#horizontal stack
h1 = np.array([4,5,6])
h2 = np.array([7,8,9])

np.hstack([h1, h2])

array([4, 5, 6, 7, 8, 9])

Load data from file

In [33]:
np.genfromtxt("data.txt", delimiter=',')

array([[ 1., 12.,  2.,  5.,  7., 77., 88.,  4.,  5.,  6.],
       [50., 66., 88., 77., 15., 56.,  8., 54.,  8., 99.],
       [ 4., 54., 84.,  5., 69.,  4., 57., 56., 97., 85.]])

In [34]:
filedata >50

NameError: name 'filedata' is not defined

In [ ]:
filedata[filedata>50]